// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcUeISZh1M3Nm1yKzjlIzmkbihwBp_qo',
    appId: '1:792066212390:web:29069bad6fb3580b3a1ce7',
    messagingSenderId: '792066212390',
    projectId: 'crypto-list-ee691',
    authDomain: 'crypto-list-ee691.firebaseapp.com',
    storageBucket: 'crypto-list-ee691.appspot.com',
    measurementId: 'G-CY051S9LYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrz4t-l0jzaMae7L2vczWIIf_rGz907nw',
    appId: '1:792066212390:android:b418817682f3fd2b3a1ce7',
    messagingSenderId: '792066212390',
    projectId: 'crypto-list-ee691',
    storageBucket: 'crypto-list-ee691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwVvTunefc7neMzXof_0Z-b8m6dHofOc',
    appId: '1:792066212390:ios:d6af20cc7b15cc0c3a1ce7',
    messagingSenderId: '792066212390',
    projectId: 'crypto-list-ee691',
    storageBucket: 'crypto-list-ee691.appspot.com',
    iosBundleId: 'com.example.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwVvTunefc7neMzXof_0Z-b8m6dHofOc',
    appId: '1:792066212390:ios:212153eb2b79df603a1ce7',
    messagingSenderId: '792066212390',
    projectId: 'crypto-list-ee691',
    storageBucket: 'crypto-list-ee691.appspot.com',
    iosBundleId: 'com.example.cryptoCoinsList.RunnerTests',
  );
}
